name: solid_test_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  go_router: ^13.2.2
  hooks_riverpod: ^2.5.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

  go_router_builder: ^2.4.1
  mockito: ^5.4.4
  solid_lints: ^0.1.5

flutter:
  uses-material-design: true
